version: '3.8'

services:
  frontend:
    image: 330107521728.dkr.ecr.us-east-1.amazonaws.com/real_project_fronted:frontend-prod-ver2
    ports:
      - "80:3000" # React uygulaması için port
    depends_on:
       -  backend 
  backend:
    image: 330107521728.dkr.ecr.us-east-1.amazonaws.com/real_project_backend:backend-prod-ver2
    ports:
      - "8092:8092" # Java Spring uygulaması için port
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database-1.cmpxn5zjrlpn.us-east-1.rds.amazonaws.com:5432/Postgres?reconnect=true"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "Devops1234"

     
